const docx = require('docx');
const fs = require('fs');
const path = require('path');

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = docx;

const doc = new Document({
    sections: [{
        properties: {},
        children: [
            // Title
            new Paragraph({
                text: "Psychiatric SOAP Note",
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
                spacing: { after: 400 },
            }),

            // Patient Info
            new Paragraph({
                children: [
                    new TextRun({ text: "Patient Name: ", bold: true }),
                    new TextRun("{patient_name}"),
                ],
                spacing: { after: 200 },
            }),

            // Subjective
            new Paragraph({
                text: "Subjective",
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
                children: [new TextRun("{subjective}")],
                spacing: { after: 200 },
            }),

            // Objective
            new Paragraph({
                text: "Objective",
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
                children: [new TextRun("{objective}")],
                spacing: { after: 200 },
            }),

            // Assessment
            new Paragraph({
                text: "Assessment",
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
                children: [new TextRun("{assessment}")],
                spacing: { after: 200 },
            }),

            // Plan
            new Paragraph({
                text: "Plan",
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
                children: [new TextRun("{plan}")],
                spacing: { after: 200 },
            }),

            // Medications
            new Paragraph({
                text: "Medications",
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 100 },
            }),
            new Paragraph({
                children: [new TextRun("{medications}")],
                spacing: { after: 200 },
            }),

            // Footer
            new Paragraph({
                text: "Generated by Alchemist AI",
                alignment: AlignmentType.CENTER,
                spacing: { before: 600 },
                children: [new TextRun({ text: "\nConfidential Medical Record", italics: true, size: 16 })]
            }),
        ],
    }],
});

Packer.toBuffer(doc).then((buffer) => {
    const outputPath = path.join(__dirname, 'template_soap.docx');
    fs.writeFileSync(outputPath, buffer);
    console.log(`Generated template_soap.docx at ${outputPath}`);
});
